---
abstract: 'To control Onkyo/Intregra AV equipment'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  English: 0
  Test::More: 0
  Test::Requires: 0
  Test::SharedFork: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Onkyo
requires:
  Carp: 0
  Device::SerialPort: 0
  Fcntl: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Socket: 0
  Symbol: 0
  Time::HiRes: 0
  constant: 0
resources:
  bugtracker: https://github.com/beanz/device-onkyo-perl/issues
  repository: git://github.com/beanz/device-onkyo-perl.git
version: 1.120740
